version: '1.0'

services:
  postgres:
    image: ankane/pgvector:v0.4.4
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=gerund_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data


