# Generated by Django 4.2.3 on 2023-07-25 01:25

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gerund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalIncoming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OriginalOutgoing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('type', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_incoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerund.originalincoming')),
            ],
        ),
        migrations.CreateModel(
            name='OutgoingVariations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('speech_binary', models.BinaryField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_outgoing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerund.originaloutgoing')),
            ],
        ),
        migrations.CreateModel(
            name='IncomingVariations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.VectorField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_incoming', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerund.originalincoming')),
            ],
        ),
    ]
