# Generated by Django 4.2.4 on 2023-08-23 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gerund', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_prompt', models.TextField()),
                ('presentation', models.TextField()),
                ('new_product', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='IncomingEmbeddings',
            new_name='IncomingEmbedding',
        ),
        migrations.RenameModel(
            old_name='OutgoingMessages',
            new_name='OutgoingMessage',
        ),
        migrations.AddField(
            model_name='question',
            name='script',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='gerund.script'),
            preserve_default=False,
        ),
    ]
