# Generated by Django 4.2.4 on 2023-08-30 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerund', '0006_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answerable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answered',
            field=models.BooleanField(default=False),
        ),
    ]
