INSERT INTO gerund_incomingembeddings (content, type, created_at, updated_at)
VALUES
-- FAIL TRIGGERS
('Ah, valeu pela ligação, mas tô feliz com o que tenho.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cara, tô satisfeito com minha operadora atual, não tô a fim de mudar.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô sem grana pra gastar com isso, melhor não.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Desculpa, mas tô no meio de um filme agora, não tô interessado.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Quem sabe em outra vida, né? Tô fora!', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tá me zoando, né? Mil reais por mês? Nem morto!', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Já me enrolei com planos assim antes, não quero passar por isso de novo.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Não ligo tanto assim, então não vale a pena pra mim.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô feliz com meu pré-pago, não quero compromisso com mensalidade.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Aqui em casa só usamos telefone pra receber cobranças, então tô fora.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O sinal da minha operadora atual já é bom o suficiente, não preciso mudar.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Nem sei onde deixei meu telefone, não sou muito ligado nisso.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô na vibe de economizar, então não tô interessado em gastar mais.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô de boa com meu plano atual, não quero mexer nisso agora.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Não ligo pra fazer chamadas, só uso o WhatsApp mesmo.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Aí, não curto compromisso, prefiro a liberdade de não ter um plano.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Não uso tanto telefone assim, então não vale a pena pra mim.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Já tenho telefone fixo em casa, não preciso de mais um plano.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Aqui em casa, cada um tem sua operadora, é uma bagunça, mas é assim que é.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô no meio de uma reunião agora, então não posso dar atenção a isso.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Já ouvi falar dessa empresa, mas não me convenceu ainda.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Meu telefone é velho, nem ia funcionar direito com um plano desse.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cara, só uso telefone pra jogar Pokémon GO, não tô interessado.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tá me falando de um plano aí, mas eu nem sei onde tá meu telefone.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Já tive problemas com operadoras antes, prefiro não arriscar.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô economizando pra comprar uma moto, então não posso gastar agora.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vou esperar uma promoção melhor, não tô com pressa pra mudar.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Moro numa área onde o sinal é ruim, então nem adianta tentar me convencer.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Não tô ligado nesse negócio de chamadas ilimitadas, não uso tanto assim.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Já tive problemas com fidelidade de planos, não quero passar por isso de novo.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Aqui em casa já tem um monte de telefones, não precisa de mais um.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô bem com meu plano pré-pago, não quero mudar pra pós.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô saindo do país em breve, então não vou precisar de um plano aqui.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Não tô interessado, valeu pela oferta.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Só uso telefone pra jogar Candy Crush, não tô afim de gastar mais.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô desempregado no momento, então não tenho condições de contratar nada.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Desculpa, mas tenho que desligar, tô atrasado pra um compromisso.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Meu telefone é basicão, não vou aproveitar todas essas chamadas ilimitadas.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô sem paciência pra falar no telefone, prefiro mensagens mesmo.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Cara, não sou muito de conversar, então não vale a pena pra mim.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Não tô afim de pagar uma fortuna por um plano, tô satisfeito com o meu atual.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Já tive problemas com cobranças indevidas, não quero passar por isso de novo.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô na vibe de desapegar das coisas, então não quero mais um plano pra cuidar.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô de férias agora, tô querendo aproveitar a paz e tranquilidade.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Não tô muito por dentro dessas tecnologias, então não vou entender direito o plano.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Prefiro gastar meu dinheiro com outras coisas, sabe? Não tô interessado.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô feliz com meu telefone velho, não quero gastar pra trocar agora.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô com um pé atrás com empresas de telefonia, já me decepcionei demais.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô esperando sair um plano melhor, não tô achando esse tão interessante.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Desculpa, mas tô ocupado demais pra dar atenção a isso agora.', 'fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
