INSERT INTO gerund_incomingembeddings (content, type, created_at, updated_at)
VALUES
-- PARTIAL FAIL TRIGGERS
('Ah, não sei, cara. Preciso pensar um pouco mais sobre isso.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hum, não tenho certeza se esse plano é para mim.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Me explica melhor, porque tô meio confuso(a) ainda.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('É, a oferta é interessante, mas preciso saber mais detalhes.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Não sei se preciso de tantas chamadas ilimitadas, entende?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tá meio caro, né? Será que não tem algo mais em conta?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Já tenho um plano de telefone, não sei se quero mudar agora.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Meus amigos e família não usam muito telefone, então não sei se vale a pena.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ah, isso de chamadas internacionais não me interessa muito, sabia?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('R$1000 por mês? Tá meio salgado, hein?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Não acho que falo tanto ao telefone para justificar esse plano.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Meu celular já tem minutos grátis, então não vejo vantagem.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tenho um plano empresarial, não sei se esse se encaixa nas minhas necessidades.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Só posso pagar até R$500 por mês, tem alguma oferta nessa faixa?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Não confio muito nessas empresas de telefonia, já tive problemas antes.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Você tem algum plano mais básico? Esse parece muito completo pra mim.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tá dizendo que é ilimitado, mas deve ter alguma pegadinha, né?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A qualidade da rede é boa mesmo? Já tive experiências ruins antes.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô preocupado(a) com a cobertura aqui na minha região.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Meu telefone é pré-pago, não sei se consigo aproveitar esse plano.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('A taxa de instalação é realmente gratuita? Sem nenhuma pegadinha?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('E se eu quiser cancelar antes dos 12 meses? Tem multa?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tenho que fazer algum contrato de fidelidade? Isso me preocupa.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Os atendentes do suporte técnico são eficientes mesmo?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Só tenho telefone fixo, não sei se o plano é vantajoso pra mim.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ah, mas eu não falo tanto assim com as pessoas, sabe?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tenho muitos créditos acumulados no meu atual plano, perderia todos?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('R$1000 é muito dinheiro pra mim, não sei se posso pagar.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tenho alguns meses de viagem planejados, não sei se vale a pena.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Já tive problemas com a fatura antes, como posso ter certeza de que isso não vai acontecer de novo?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tô satisfeito(a) com meu plano atual, não sei se quero mudar.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O preço é fixo mesmo? Nada de aumentos surpresa depois?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Minha família usa muitas chamadas de vídeo, isso está incluso?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tenho uma promoção no meu atual plano, não quero perder isso.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Já ouvi falar de problemas de sinal com outras operadoras, isso não acontece com vocês, né?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Não costumo fazer chamadas internacionais, então não sei se vale a pena.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Posso testar o plano por um mês antes de decidir definitivamente?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('O suporte técnico funciona bem mesmo durante a madrugada?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tenho que pagar algum adiantamento? Isso me deixa apreensivo(a).', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ah, mas eu já tenho um plano antigo com a Viva, acho que não posso mudar.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Não sei se confio em chamadas ilimitadas, parece bom demais pra ser verdade.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('R$1000 por mês é muito dinheiro, preciso pensar com calma.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Essa taxa de instalação gratuita é só por tempo limitado?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tem algum período de carência antes de poder usar todas as vantagens?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Minha conta telefônica atual já é alta, não sei se posso pagar mais.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vocês têm algum plano com mais internet? Preciso de uma franquia maior.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Minha família mora longe, esse plano inclui chamadas para outros estados?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Tem alguma promoção para quem indica amigos? Conheço algumas pessoas interessadas.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Essa oferta é exclusiva para novos clientes ou também vale para quem já é cliente?', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Preciso saber mais sobre as formas de pagamento disponíveis, isso é importante pra mim.', 'partial_fail_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
