INSERT INTO gerund_incomingembeddings (content, type, created_at, updated_at)
VALUES
-- SUCCESS TRIGGERS
('Caramba, chamadas ilimitadas? Isso parece bom demais!', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Esse preço está muito bom! Quero saber mais detalhes.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ah, é para qualquer telefone? Isso é ótimo!', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Pagar apenas R$1000 por mês é bem mais em conta do que eu imaginava.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Uau, desconto de 100% na taxa de instalação? Tô interessado!', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ligação ilimitada pra qualquer lugar? Parece um sonho!', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Eu tenho parentes em São Paulo e no Rio de Janeiro, então isso seria perfeito pra mim!', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Se eu pudesse fazer chamadas internacionais sem me preocupar com o preço, seria incrível.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Quero ter a liberdade de ligar para qualquer pessoa a qualquer momento, sem me preocupar com a conta.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Se o suporte técnico realmente funciona 24 horas por dia, sete dias por semana, já é um ponto positivo pra mim.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Se eu ligar agora, consigo atendimento em menos de cinco minutos?', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Já tive problemas com outros provedores de telefonia, então um bom suporte técnico faz toda a diferença.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Chamadas ilimitadas nacionais e internacionais por esse preço? Preciso saber mais!', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Se a maioria da rede é em fibra óptica, isso significa uma conexão mais rápida, certo?', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Quero ter a tranquilidade de fazer ligações sem me preocupar com custos adicionais.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Se eu pudesse ligar para meus amigos e parentes em qualquer lugar do Brasil sem restrições, seria maravilhoso.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Estou cansado de ficar limitado nas chamadas. Quero poder falar o quanto eu quiser!', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Com o plano "Eu Aqui e Lá", parece que finalmente encontrei a solução que eu estava procurando.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Eu trabalho com clientes internacionais, então chamadas internacionais inclusas seriam perfeitas para mim.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Se eu pudesse fazer chamadas ilimitadas para telefones móveis, seria realmente útil para o meu dia a dia.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Poder ligar para qualquer lugar do mundo por um preço fixo me deixa bem interessado.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Eu sempre quis ter um plano com chamadas ilimitadas, mas os preços eram sempre altos. Esse é diferente?', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Se eu pudesse economizar na taxa de instalação, já seria um bom começo.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Quero a liberdade de ligar para quem eu quiser, sem pensar nas tarifas.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Com esse plano, eu não precisaria mais me preocupar em controlar a duração das minhas chamadas.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Se o atendimento é garantido em menos de cinco minutos, isso é um alívio!', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Eu sou uma pessoa que fala muito ao telefone, então chamadas ilimitadas seriam perfeitas para mim.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Eu tenho amigos e familiares em Belo Horizonte, São Paulo e Rio de Janeiro, então esse plano seria ideal.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Poder fazer chamadas internacionais sem pagar a mais é algo que me interessa muito.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Se eu pudesse ligar para qualquer telefone fixo ou móvel, isso facilitaria minha vida.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Quero ter um plano que me permita ligar para qualquer lugar, sem exceções.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Se a qualidade da rede é boa, isso faz toda a diferença na hora de fazer ligações.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Com esse plano, eu poderia manter contato com meus amigos que estão fora do país sem me preocupar com a conta.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Se eu pudesse ligar para qualquer operadora sem restrições, seria incrível.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Chamadas ilimitadas e um bom suporte técnico são dois pontos que me chamam a atenção.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Eu gosto de falar ao telefone e ter um plano com chamadas ilimitadas seria muito conveniente para mim.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Se eu pudesse ligar para qualquer lugar do Brasil sem pagar a mais, seria uma grande vantagem.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Quero poder ligar para qualquer pessoa, em qualquer momento, sem ter que me preocupar com limitações.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Com chamadas ilimitadas, eu não precisaria mais me preocupar em controlar o tempo das minhas ligações.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Se eu pudesse fazer chamadas internacionais sem me preocupar com o preço, seria um grande benefício.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Eu costumo ligar para telefones móveis com frequência, então um plano com chamadas ilimitadas seria perfeito para mim.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Com o plano "Eu Aqui e Lá", eu teria a liberdade de falar com meus parentes que estão em diferentes estados.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Se a rede da Viva é quase toda em fibra óptica, isso significa que a conexão seria mais estável, certo?', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Eu já tive experiências ruins com outros provedores de telefonia, então um bom suporte técnico seria essencial para mim.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Chamadas ilimitadas nacionais e internacionais por esse preço? Isso realmente me chama a atenção.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Se eu pudesse ligar para qualquer lugar do Brasil sem restrições, seria muito prático para mim.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Eu gosto de falar bastante ao telefone, então chamadas ilimitadas seriam um grande benefício para mim.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Com esse plano, eu não precisaria me preocupar com custos adicionais por chamadas longas ou internacionais.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Se eu pudesse fazer chamadas ilimitadas para telefones móveis, isso seria muito útil no meu dia a dia.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Eu sempre quis ter um plano com chamadas ilimitadas, mas os preços eram sempre muito altos. Esse parece mais acessível.', 'success_trigger', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
