INSERT INTO gerund_outgoingmessages (content, type, created_at, updated_at, answer_id)
VALUES
-- FIRST ANSWER --
('"Viva 100: 100 minutos de ligações locais por R$50 por mês.
 Viva 300: 300 minutos de ligações locais por R$80 por mês.
 Viva ilimitado: 500 minutos de ligações locais por R$90 por mês.
 Viva ilimitado plus: 800 minutos de ligações locais por R$95 por mês.
 Viva ilimitado plus extra: minutos ilimitados de ligações locais por R$120 por mês."', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
-- SECOND ANSWER --
('"Viva 100 mobile: 100 minutos de ligações locais móveis por R$50 por mês.
 Viva 300 mobile: 300 minutos de ligações locais móveis por R$80 por mês.
 Viva ilimitado mobile: 500 minutos de ligações locais móveis por R$90 por mês.
 Viva ilimitado plus mobile: 800 minutos de ligações locais móveis por R$95 por mês.
 Viva ilimitado plus extra mobile: minutos ilimitados de ligações locais móveis por R$120 por mês."', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
-- THIRD ANSWER --
('O Viva ilimitado plus inclui 800 minutos de ligações locais, enquanto o Viva ilimitado plus extra oferece minutos ilimitados de ligações locais.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('O Viva ilimitado plus te dá 800 minutos para fazer ligações locais, já o Viva ilimitado plus extra te oferece ligações locais ilimitadas.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('No Viva ilimitado plus, você tem 800 minutos de ligações locais, mas no Viva ilimitado plus extra, as ligações locais são ilimitadas.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Com o Viva ilimitado plus, você terá 800 minutos para falar em ligações locais, enquanto o Viva ilimitado plus extra oferece ligações locais ilimitadas.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('No Viva ilimitado plus, você tem uma franquia de 800 minutos para ligações locais, mas no Viva ilimitado plus extra, as ligações locais são ilimitadas.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('O Viva ilimitado plus inclui 800 minutos para ligações locais, mas se você escolher o Viva ilimitado plus extra, terá ligações locais ilimitadas.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
-- FOURTH ANSWER --
('Não há contrato mínimo para assinar os planos, exceto para o Plano "Eu Aqui e Lá", que requer um contrato de 24 meses.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Na maioria dos planos, não há contrato mínimo, você pode assinar sem compromisso. Mas para o Plano "Eu Aqui e Lá", é necessário um contrato de 24 meses.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Os planos em geral não têm contrato mínimo, mas o Plano "Eu Aqui e Lá" exige um contrato de 24 meses.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Ao assinar a maioria dos planos, você não fica preso a um contrato mínimo. A exceção é o Plano "Eu Aqui e Lá", que requer um compromisso de 24 meses.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Você pode adquirir os planos sem precisar se comprometer com um contrato mínimo, exceto para o Plano "Eu Aqui e Lá", que tem um contrato de 24 meses.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Geralmente, os planos não têm exigência de contrato mínimo, mas no caso do Plano "Eu Aqui e Lá", é necessário assinar um contrato de 24 meses.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
-- FIFTH ANSWER --
('Sim, você pode escolher planos diferentes para telefonia fixa e móvel. A Viva oferece planos separados para cada tipo de serviço.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Com a Viva, você tem a liberdade de escolher planos diferentes para telefonia fixa e móvel. Oferecemos opções separadas para cada tipo de serviço.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Sim, é possível optar por planos distintos para telefonia fixa e móvel. A Viva disponibiliza diferentes opções para cada um desses serviços.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Na Viva, você tem a flexibilidade de escolher planos específicos para telefonia fixa e móvel. Temos opções separadas para atender às suas necessidades.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Com a Viva, você pode personalizar seus planos de acordo com a telefonia fixa e móvel. Oferecemos opções individuais para cada tipo de serviço.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Na Viva, você tem a liberdade de selecionar planos distintos para telefonia fixa e móvel. Temos ofertas separadas para garantir a melhor experiência em ambos os serviços.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
-- SIXTH ANSWER --
('A taxa de instalação é de R$1000, mas se você assinar um contrato de 24 meses, receberá um desconto de 90% sobre a instalação. Isso significa que você pagará apenas R$100 pela taxa de instalação. No entanto, se você cancelar antes do prazo, será cobrada a totalidade da instalação, proporcional ao tempo restante do contrato.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6),
('A taxa de instalação é R$1000, mas se você optar por um contrato de 24 meses, receberá um desconto de 90% sobre a instalação, pagando apenas R$100. No entanto, caso cancele antes do prazo, será cobrada a taxa restante proporcional ao tempo restante do contrato.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6),
('Ao adquirir nossos serviços, há uma taxa de instalação de R$1000. Porém, se você optar pelo contrato de 24 meses, receberá um desconto de 90% e pagará apenas R$100. Vale ressaltar que, em caso de cancelamento antecipado, será cobrada a taxa proporcional ao tempo restante do contrato.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6),
('A taxa de instalação é de R$1000, mas, ao assinar um contrato de 24 meses, você receberá um desconto de 90%, pagando somente R$100 pela instalação. É importante lembrar que, em caso de cancelamento antes do prazo, será cobrada a taxa proporcional ao tempo restante do contrato.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6),
('Para instalar os serviços, é cobrada uma taxa de R$1000. No entanto, ao optar por um contrato de 24 meses, você recebe um desconto de 90% e paga apenas R$100 pela instalação. É necessário mencionar que, caso cancele antes do prazo, será cobrada a taxa proporcional ao tempo restante do contrato.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6),
('Ao contratar nossos serviços, você pagará uma taxa de instalação de R$1000. Porém, ao optar pelo contrato de 24 meses, terá um desconto de 90%, pagando apenas R$100 pela instalação. É válido lembrar que, caso decida cancelar antes do prazo, será cobrada a taxa proporcional ao tempo restante do contrato.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 6),
-- SEVENTH ANSWER --
('Sim, o plano "Eu Aqui e Lá" inclui chamadas internacionais. Você poderá fazer chamadas para qualquer telefone, tanto local quanto internacionalmente.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 7),
('Com o plano "Eu Aqui e Lá", você pode fazer chamadas internacionais para qualquer telefone, seja ele local ou no exterior.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 7),
('Sim, o plano "Eu Aqui e Lá" oferece chamadas internacionais. Com ele, você pode ligar para qualquer telefone, seja local ou internacional.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 7),
('O plano "Eu Aqui e Lá" inclui chamadas internacionais, permitindo que você entre em contato com telefones locais e internacionais.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 7),
('Com o plano "Eu Aqui e Lá", você tem acesso a chamadas internacionais. Isso significa que você pode ligar para qualquer telefone, independentemente de ser local ou internacional.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 7),
('Sim, chamadas internacionais estão incluídas no plano "Eu Aqui e Lá". Com ele, você pode ligar para telefones tanto no Brasil quanto no exterior.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 7),
-- EIGTH ANSWER --
('Além de Belo Horizonte, São Paulo e Rio de Janeiro, a Viva não atua em outras cidades no momento.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 8),
('A Viva opera atualmente apenas nas cidades de Belo Horizonte, São Paulo e Rio de Janeiro.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 8),
('No momento, nossos serviços estão disponíveis exclusivamente em Belo Horizonte, São Paulo e Rio de Janeiro.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 8),
('A Viva concentra suas operações nas cidades de Belo Horizonte, São Paulo e Rio de Janeiro.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 8),
('Atualmente, nossos serviços estão limitados às cidades de Belo Horizonte, São Paulo e Rio de Janeiro.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 8),
('Nossas atividades estão focadas nas cidades de Belo Horizonte, São Paulo e Rio de Janeiro.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 8),
-- NINETH ANSWER --
('Para entrar em contato com o suporte ao cliente da Viva, você pode ligar para o nosso número de atendimento, que funciona 24 horas por dia, sete dias por semana. O tempo de espera é garantido em menos de cinco minutos.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 9),
('Se precisar entrar em contato com nosso suporte ao cliente, você pode ligar para o nosso número de atendimento, que está disponível 24 horas por dia, sete dias por semana. Garantimos um tempo de espera de menos de cinco minutos.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 9),
('Caso necessite falar com nosso suporte ao cliente, basta ligar para o número de atendimento, que está disponível o tempo todo, 24 horas por dia, sete dias por semana. Você será atendido em menos de cinco minutos, sem demoras.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 9),
('Para obter suporte ao cliente, é só ligar para o nosso número de atendimento, que funciona 24 horas por dia, sete dias por semana. Temos o compromisso de atendê-lo em menos de cinco minutos, sem demoras.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 9),
('Se precisar de assistência do nosso suporte ao cliente, é só ligar para o número de atendimento, que está disponível o tempo todo, 24 horas por dia, sete dias por semana. Garantimos que você será atendido em menos de cinco minutos, sem esperar muito.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 9),
('Caso precise entrar em contato com nosso suporte ao cliente, basta ligar para o nosso número de atendimento, que funciona 24 horas por dia, sete dias por semana. Nosso objetivo é atender sua ligação em menos de cinco minutos, proporcionando um serviço ágil e eficiente.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 9),
-- TENTH ANSWER --
('As opções de pagamento disponíveis são débito em conta ou cartão de crédito. Você pode escolher a forma de pagamento que for mais conveniente para você.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 10),
('Para sua comodidade, oferecemos duas opções de pagamento: débito em conta ou cartão de crédito. Assim, você pode escolher a forma que mais lhe convém.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 10),
('Pensando na sua praticidade, disponibilizamos duas opções de pagamento: débito em conta ou cartão de crédito. Assim, você tem a liberdade de escolher a opção mais conveniente para você.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 10),
('Temos duas opções de pagamento para facilitar sua vida: débito em conta ou cartão de crédito. Dessa forma, você pode optar pela forma de pagamento que melhor se adequa às suas necessidades.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 10),
('Para tornar o processo de pagamento mais flexível, oferecemos duas opções: débito em conta ou cartão de crédito. Assim, você pode escolher aquela que se encaixa melhor em sua rotina.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 10),
('Oferecemos duas opções de pagamento para tornar sua experiência mais conveniente: débito em conta ou cartão de crédito. Você tem a liberdade de escolher a opção que melhor se adapta ao seu estilo de vida.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 10),
-- ELEVENTH ANSWER --
('Não há limite de dados para os planos de telefonia móvel. No entanto, é importante lembrar que os planos da Viva incluem apenas chamadas de voz. Para internet, você precisará entrar em contato com um provedor de internet da sua cidade.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 11),
('Nossos planos de telefonia móvel não possuem limite de dados, permitindo que você navegue na internet sem preocupações. No entanto, é importante ressaltar que nossos planos são focados em chamadas de voz. Caso deseje contratar serviços de internet, recomendamos entrar em contato com um provedor de sua cidade.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 11),
('Nosso serviço de telefonia móvel não tem restrição de dados, garantindo que você possa desfrutar da internet sem preocupações. No entanto, é importante lembrar que nossos planos são específicos para chamadas de voz. Caso deseje contratar serviços de internet, é necessário contatar um provedor local.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 11),
('Em nossos planos de telefonia móvel, você tem total liberdade para utilizar seus dados sem limite. No entanto, é importante ter em mente que nossos serviços são voltados para chamadas de voz. Caso queira contratar um serviço de internet, recomendamos procurar um provedor de sua cidade.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 11),
('Nossos planos de telefonia móvel não possuem restrição de dados, o que significa que você pode utilizar a internet à vontade. É válido ressaltar, porém, que nossos planos são focados em chamadas de voz. Para serviços de internet, é necessário entrar em contato com um provedor local.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 11),
('Não há limite de dados em nossos planos de telefonia móvel, permitindo que você desfrute da internet sem preocupações. No entanto, é importante salientar que nossos serviços são direcionados para chamadas de voz. Caso queira contratar um serviço de internet, recomendamos procurar um provedor de sua cidade.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 11),
-- TWELVETH ANSWER --
('A Viva oferece apenas serviços de telefonia fixa e móvel. Para internet ou TV a cabo, recomendamos que você entre em contato com os provedores especializados nessas áreas.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 12),
('A Viva é especializada em serviços de telefonia fixa e móvel, oferecendo soluções de comunicação de alta qualidade. Para internet ou TV a cabo, sugerimos que entre em contato com os provedores especializados nessas áreas, que poderão atender às suas necessidades específicas.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 12),
('Nossos serviços são focados em telefonia fixa e móvel, oferecendo uma ampla gama de opções de comunicação. Caso esteja interessado em internet ou TV a cabo, recomendamos que procure provedores especializados nessas áreas, que poderão fornecer os serviços adequados para você.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 12),
('Na Viva, nosso objetivo é fornecer serviços excelentes de telefonia fixa e móvel. No entanto, para internet ou TV a cabo, é recomendável contatar provedores especializados nesses serviços, que poderão atender suas demandas de forma mais adequada.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 12),
('Somos especialistas em telefonia fixa e móvel, oferecendo soluções completas de comunicação. Caso necessite de internet ou TV a cabo, recomendamos que entre emcontato com provedores especializados nessas áreas, que poderão oferecer os serviços específicos que você procura.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 12),
('Na Viva, concentramos nossos esforços em fornecer serviços de telefonia fixa e móvel de qualidade. Para internet ou TV a cabo, é mais adequado buscar os provedores especializados nesses serviços, que possuem o conhecimento e as opções específicas para atender às suas necessidades.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 12),
-- THIRTEENTH ANSWER --
('Sim, é possível transferir seu número de telefone atual para a Viva. Como cliente novo, você terá a opção de transferir seu número existente ou obter um novo número da Viva.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 13),
('Temos boas notícias! Na Viva, você pode trazer seu número atual para nós. É só nos informar que deseja fazer a transferência e cuidaremos de tudo para que você continue usando o mesmo número com a gente.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 13),
('Fique tranquilo! Aqui na Viva, possibilitamos a transferência do seu número de telefone atual. Isso significa que você não precisa se preocupar em mudar seu número, caso não queira. A escolha é sua!', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 13),
('Não se preocupe, podemos cuidar disso para você. Se você é um cliente novo e deseja manter seu número atual, a Viva oferece a opção de transferência. Assim, você não precisa se preocupar em informar um novo número a todos os seus contatos.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 13),
('Queremos facilitar sua vida, então é possível trazer seu número atual para a Viva. Como cliente novo, você tem a liberdade de escolher se deseja transferir seu número existente ou obter um novo número da Viva. A decisão é sua!', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 13),
('Estamos aqui para ajudar! Na Viva, permitimos que você mantenha seu número atual. Se você já tem um número de telefone que adora, pode transferi-lo para a Viva sem problemas. Assim, você não precisa se preocupar em informar um novo número a todos os seus contatos.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 13),
-- FOURTEENTH ANSWER --
('A Viva não oferece serviços de internet. Recomendamos que você entre em contato com um provedor de internet da sua cidade para obter informações sobre as velocidades disponíveis.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 14),
('A Viva se dedica a fornecer os melhores serviços de telefonia móvel. Infelizmente, não oferecemos internet, mas ficaremos felizes em ajudá-lo a encontrar um provedor de internet confiável em sua região. Entre em contato com um provedor local para obter informações sobre as velocidades disponíveis e aproveite o melhor da conectividade.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 14),
('Na Viva, nosso foco é oferecer excelência em serviços de telefonia. Embora não tenhamos internet, podemos ajudá-lo a encontrar um provedor confiável em sua cidade. Recomendamos que você entre em contato com um provedor de internet local para saber mais sobre as opções de velocidade disponíveis.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 14),
('Sabemos que a internet é essencial hoje em dia, mas, infelizmente, a Viva não oferece serviços de internet. No entanto, estamos aqui para ajudá-lo a encontrar um provedor confiável na sua região. Entre em contato com os provedores de internet locais para obter informações sobre as velocidades disponíveis e aproveitar ao máximo sua conexão.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 14),
('Nossa especialidade é fornecer serviços de telefonia móvel excepcionais, mas, infelizmente, não oferecemos internet. Se você estiver procurando por um provedor de internet em sua cidade, podemos ajudá-lo a encontrar as opções disponíveis. Entre em contato com os provedores locais para obter informações sobre as velocidades que eles oferecem.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 14),
('Embora não ofereçamos serviços de internet, na Viva estamos prontos para ajudá-lo a encontrar o provedor certo para suas necessidades. Recomendamos que você entre em contato com os provedores de internet da sua cidade para obter informações detalhadas sobre as velocidades disponíveis e aproveitar uma conexão rápida e confiável.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 14),
-- FIFTEENTH ANSWER --
('Com exceção do plano "Eu Aqui e Lá", os demais planos cobram tarifas adicionais para chamadas nacionais e internacionais. Essas tarifas variam de acordo com o destino da chamada.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 15),
('Nosso plano "Eu Aqui e Lá" é realmente especial! Ao contrário dos outros planos, nele você não precisa se preocupar com tarifas adicionais para chamadas nacionais e internacionais. Para os demais planos, é importante lembrar que as tarifas variam de acordo com o destino da chamada.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 15),
('Estamos aqui para esclarecer os detalhes sobre os nossos planos. Com exceção do plano "Eu Aqui e Lá", é importante saber que os outros planos cobram tarifas adicionais para chamadas nacionais e internacionais. Essas tarifas variam dependendo do destino da chamada.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 15),
('É bom saber que você está interessado nos nossos planos! Exceto pelo plano "Eu Aqui e Lá", é importante destacar que os demais planos da Viva têm tarifas adicionais para chamadas nacionais e internacionais. Fique tranquilo, as tarifas são variáveis e dependem do destino da chamada.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 15),
('Vamos falar sobre os detalhes dos nossos planos! Com exceção do plano "Eu Aqui e Lá", é válido lembrar que os outros planos da Viva incluem tarifas adicionais para chamadas nacionais e internacionais. As tarifas variam de acordo com o local para onde você estiver ligando.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 15),
('Os planos da Viva oferecem muitas vantagens, mas é importante mencionar que, com exceção do plano "Eu Aqui e Lá", os demais planos têm tarifas adicionais para chamadas nacionais e internacionais. Essas tarifas variam dependendo do destino da chamada. Estamos aqui para ajudá-lo a escolher o plano que melhor atende às suas necessidades.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 15),
-- SIXTEENTH ANSWER --
('O tempo de instalação do serviço pode variar, mas nos esforçamos para realizar a instalação o mais rápido possível após a contratação. Nosso objetivo é garantir que você tenha acesso aos serviços da Viva o mais breve possível.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 16),
('Estamos ansiosos para tê-lo como nosso cliente! O tempo de instalação do serviço pode variar, mas nossa equipe trabalha diligentemente para realizar a instalação o mais rápido possível após a contratação. Nosso objetivo é garantir que você tenha acesso aos serviços da Viva o mais breve possível e aproveite tudo que temos a oferecer.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 16),
('Valorizamos sua escolha em nos considerar como seu provedor de serviços. Embora o tempo de instalação possa variar, tenha certeza de que estamos comprometidos em realizar a instalação o mais rápido possível após a contratação. Queremos que você comece a aproveitar os serviços da Viva o mais breve possível.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 16),
('Sabemos que você está ansioso para começar a desfrutar dos nossos serviços. Embora o tempo de instalação possa variar, nossa equipe se esforça para realizar a instalação o mais rápido possível após a contratação. Queremos que você tenha acesso aos serviços da Viva o mais breve possível e aproveite todas as vantagensque oferecemos.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 16),
('Seu tempo é valioso, e entendemos que você deseja começar a desfrutar dos serviços da Viva o mais rápido possível. Embora o tempo de instalação possa variar, nossa equipe está empenhada em realizar a instalação logo após a contratação. Queremos garantir que você tenha acesso aos nossos serviços o mais breve possível.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 16),
('Estamos aqui para tornar sua transição para a Viva o mais suave possível. Embora o tempo de instalação possa variar, estamos comprometidos em realizar a instalação rapidamente após a contratação. Nossa equipe está pronta para garantir que você tenha acesso aos serviços da Viva em tempo hábil.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 16),
-- SEVENTEENTH ANSWER --
('Exceto para o novo Plano "Eu Aqui e Lá", os demais planos não têm fidelidade. Você pode cancelar o serviço a qualquer momento sem custos adicionais. No entanto, se você assinar o Plano "Eu Aqui e Lá" com o contrato de 24 meses, será necessário cumprir o prazo mínimo estabelecido. Em caso de cancelamento antes do prazo, será cobrada a totalidade da instalação proporcional ao tempo restante do contrato.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 17),
('Na Viva, oferecemos flexibilidade para nossos clientes. Com exceção do Plano "Eu Aqui e Lá", nossos demais planos não possuem fidelidade. Isso significa que você pode cancelar o serviço a qualquer momento, sem custos adicionais. No entanto, se você escolher assinar o Plano "Eu Aqui e Lá" com o contrato de 24 meses, é importante lembrar que será necessário cumprir o prazo mínimo estabelecido. Em caso de cancelamento antes do prazo, será cobrada a totalidade da instalação proporcional ao tempo restante do contrato.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 17),
('Valorizamos a liberdade de nossos clientes na Viva. Com exceção do Plano "Eu Aqui e Lá", você pode cancelar qualquer um de nossos planos a qualquer momento, sem custos adicionais. No entanto, é importante lembrar que, caso você opte pelo Plano "Eu Aqui e Lá" com o contrato de 24 meses, será necessário cumprir o prazo mínimo estabelecido. Se ocorrer o cancelamento antes do prazo, será cobrada a totalidade da instalação proporcional ao tempo restante do contrato.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 17),
('Queremos oferecer a melhor experiência para nossos clientes na Viva. Por isso, nossos planos não têm fidelidade, exceto pelo Plano "Eu Aqui e Lá". Isso significa que você pode cancelar qualquer um dos nossos planos a qualquer momento, sem custos adicionais. No entanto, é importante lembrar que, se você optar pelo Plano "Eu Aqui e Lá" com o contrato de 24 meses, será necessário cumprir o prazo mínimo estabelecido. Caso ocorra o cancelamento antes do prazo, será cobrada a totalidade da instalação proporcional ao tempo restante do contrato.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 17),
('Entendemos a importância da flexibilidade para nossos clientes. Na Viva, todos os nossos planos, exceto o Plano "Eu Aqui e Lá", não possuem fidelidade. Isso significa que você pode cancelar o serviço quando quiser, sem custos adicionais. No entanto, é importante mencionar que, caso você escolha assinar o Plano "Eu Aqui e Lá" com o contrato de 24 meses, será necessário cumprir o prazo mínimo estabelecido. Se ocorrer o cancelamento antes do prazo, será cobrada a totalidade da instalação proporcional ao tempo restante do contrato.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 17),
('Queremos oferecer a liberdade de escolha para nossos clientes na Viva. Com exceção do Plano "Eu Aqui e Lá", você pode cancelar qualquer um de nossos planos quando quiser, sem custos adicionais. No entanto, é importante lembrar que, se você optar pelo Plano "Eu Aqui e Lá" com o contrato de 24 meses, será necessário cumprir o prazo mínimo estabelecido. Em caso de cancelamento antes do prazo, será cobrada a totalidade da instalação proporcional ao tempo restante do contrato.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 17),
-- EIGHTEENTH ANSWER --
('Sim, a Viva possui o melhor suporte técnico do país. Nosso suporte técnico funciona 24 horas por dia, sete dias por semana, e estamos prontos para ajudar em qualquer problema técnico que você possa enfrentar.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 18),
('Nós nos orgulhamos de oferecer o melhor suporte técnico do país aqui na Viva. Nossa equipe está disponível 24 horas por dia, sete dias por semana, para ajudar você com qualquer problema técnico que possa surgir. Pode contar conosco!', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 18),
('A satisfação dos nossos clientes é a nossa prioridade. Por isso, investimos em um suporte técnico de excelência. Aqui na Viva, nossa equipe está pronta para ajudar você 24 horas por dia, sete dias por semana, em qualquer problema técnico que você possa enfrentar. Conte conosco para resolver qualquer questão!', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 18),
('Na Viva, acreditamos em oferecer o melhor suporte técnico para nossos clientes. Nossa equipe está disponível 24 horas por dia, sete dias por semana, para ajudar você com qualquer problema técnico que possa surgir. Não importa a hora ou o dia, estamos aqui para garantir que suas necessidades sejam atendidas.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 18),
('Sua tranquilidade é importante para nós. Aqui na Viva, temos o melhor suporte técnico do país, disponível 24 horas por dia, sete dias por semana. Se você enfrentar qualquer problema técnico, nossa equipe estará pronta para ajudar e resolver a questão o mais rápido possível.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 18),
('Estamos comprometidos em oferecer a melhor experiência para nossos clientes. Com o suporte técnico da Viva, vocêpode ficar tranquilo. Temos uma equipe especializada disponível 24 horas por dia, sete dias por semana, pronta para ajudar em qualquer problema técnico que você possa enfrentar. Conte conosco para resolver suas questões de forma rápida e eficiente.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 18),
-- NINETEENTH ANSWER --
('Não há limite de minutos para chamadas locais nos planos da Viva, com exceção dos planos que já oferecem minutos ilimitados, como o Viva ilimitado e o Viva ilimitado plus.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 19),
('Aqui na Viva, valorizamos sua liberdade para fazer chamadas locais. A maioria dos nossos planos não possui limite de minutos para chamadas locais. No entanto, é importante mencionar que temos planos especiais, como o Viva ilimitado e o Viva ilimitado plus, que oferecem minutos ilimitados. Assim, você pode escolher o plano que melhor atende às suas necessidades de comunicação.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 19),
('Na Viva, queremos que você aproveite suas chamadas locais sem preocupações. A maioria dos nossos planos não possui limite de minutos para chamadas locais. No entanto, temos opções ainda mais vantajosas, como o Viva ilimitado e o Viva ilimitado plus, que oferecem minutos ilimitados. Escolha o plano que melhor se encaixa no seu estilo de comunicação!', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 19),
('Sua liberdade é importante para nós. Aqui na Viva, a maioria dos nossos planos não possui limite de minutos para chamadas locais. No entanto, temos planos especiais, como o Viva ilimitado e o Viva ilimitado plus, que oferecem minutos ilimitados. Assim, você pode aproveitar suas chamadas sem se preocupar com limites.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 19),
('Queremos que você tenha total liberdade para fazer chamadas locais. Na Viva, a maioria dos nossos planos não possui limite de minutos para chamadas locais. No entanto, temos opções ainda mais vantajosas, como o Viva ilimitado e o Viva ilimitado plus, que oferecem minutos ilimitados. Escolha o plano que melhor se adapta às suas necessidades de comunicação.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 19),
('Aqui na Viva, queremos que você aproveite ao máximo suas chamadas locais. A maioria dos nossos planos não possui limite de minutos para chamadas locais. No entanto, temos planos especiais, como o Viva ilimitado e o Viva ilimitado plus, que oferecem minutos ilimitados. Assim, você pode conversar à vontade sem se preocupar com restrições de tempo.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 19),
-- TWENTYETH ANSWER --
('O Plano "Eu Aqui e Lá" oferece chamadas ilimitadas para qualquer telefone, incluindo chamadas locais, nacionais e internacionais para telefones fixos e móveis. Além disso, o plano possui um desconto de 100% na taxa de instalação.', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 20),
('O Plano "Eu Aqui e Lá" é perfeito para você! Com ele, você tem chamadas ilimitadas para qualquer telefone, tanto localmente quanto nacionalmente, incluindo chamadas internacionais para telefones fixos e móveis. E tem mais: você não precisa se preocupar com taxas de instalação, pois oferecemos um desconto de 100%!', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 20),
('Estou aqui para falar sobre o incrível Plano "Eu Aqui e Lá". Com ele, você tem a liberdade de fazer chamadas ilimitadas para qualquer telefone, seja ele local, nacional ou internacional, tanto fixo quanto móvel. E sabe o que é melhor? Nós garantimos a você um desconto de 100% na taxa de instalação!', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 20),
('Você está procurando por um plano completo? O Plano "Eu Aqui e Lá" oferece exatamente o que você precisa! Com ele, você tem chamadas ilimitadas para qualquer telefone, em qualquer lugar, seja local, nacional ou internacional, abrangendo telefones fixos e móveis. E tem mais: a taxa de instalação é completamente gratuita!', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 20),
('Deixe-me contar sobre o incrível Plano "Eu Aqui e Lá". Com ele, você pode desfrutar de chamadas ilimitadas para qualquer telefone, em qualquer parte do mundo, sejam elas locais, nacionais ou internacionais. E o melhor de tudo? A taxa de instalação é totalmente isenta!', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 20),
('Você sabia que o Plano "Eu Aqui e Lá" oferece chamadas ilimitadas para qualquer telefone? Isso mesmo! Você pode fazer ligações locais, nacionais e até internacionais, tanto para telefones fixos quanto móveis. E não se preocupe com taxas de instalação, pois você terá um desconto de 100%!', 'answer', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 20);