INSERT INTO gerund_outgoingmessages (content, type, created_at, updated_at)
VALUES
-- FAIL ENDINGS
('Entendo perfeitamente, não tem problema. Agradeço pela sua atenção. Tenha um ótimo dia e estamos à disposição caso mude de ideia.', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Sem problemas, entendo que o serviço não se encaixa nas suas necessidades no momento. Agradeço pela conversa e fico à disposição caso queira reconsiderar no futuro.', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Compreendo sua posição e respeito sua decisão. Agradeço pela sua atenção e desejo a você um dia incrível. Se mudar de ideia, estaremos aqui para ajudar.', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Obrigado por ouvir a minha oferta. Sei que nem sempre é o momento certo para todos. Agradeço pela sua atenção e estamos aqui caso mude de ideia no futuro.', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Entendo que este não seja o serviço que você está procurando agora. Agradeço pela gentileza de me ouvir e estamos à disposição caso decida considerar nossos serviços em algum momento.', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fico feliz por termos tido essa conversa, mesmo que não tenha sido do seu interesse no momento. Agradeço pela atenção e estaremos aqui se precisar de qualquer coisa no futuro.', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Percebo que o serviço não é o que você está buscando atualmente. Agradeço pela sua disponibilidade em conversar e desejo a você um dia excelente. Caso mude de ideia, estamos aqui para ajudar.', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Entendo que não seja o momento certo para você. Agradeço pela sua atenção e compreendo completamente. Tenha um dia maravilhoso e lembre-se de nós se algo mudar.', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Obrigado por dedicar um momento para ouvir sobre nosso serviço. Sei que nem sempre é o que se procura. Agradeço pela consideração e estamos aqui caso você decida reconsiderar.', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fico grato pela sua atenção. Entendo que este não seja o serviço que você está procurando no momento. Se mudar de ideia, estaremos disponíveis para ajudá-lo. Tenha um ótimo dia!', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Compreendo que o serviço não atenda às suas necessidades neste momento. Agradeço pela sua cortesia em me ouvir e fico à disposição caso você mude de ideia futuramente. Tenha um dia fantástico!', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Agradeço sinceramente por ouvir sobre nosso serviço. Sei que nem sempre é o que se procura no momento. Estaremos à disposição caso haja qualquer mudança de interesse. Tenha um dia incrível!', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Obrigado por sua atenção. Sei que este não é o momento certo para você. Agradeço pela gentileza e compreendo sua decisão. Estamos aqui caso você mude de ideia. Tenha um excelente dia!', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Percebo que o serviço não se encaixa no que você está procurando. Agradeço por tirar um tempo para conversar e estamos à disposição caso mude de ideia. Tenha um dia maravilhoso!', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Entendo que o serviço não atenda às suas necessidades no momento. Agradeço pela atenção e respeito sua decisão. Se mudar de ideia, não hesite em entrar em contato. Tenha um dia fantástico!', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Obrigado por considerar nossa oferta. Sei que nem sempre é o que se procura. Agradeço pela gentileza em me ouvir e estamos disponíveis para ajudar caso mude de ideia. Tenha um ótimo dia!', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Compreendo que este não seja o serviço que você está procurando no momento. Agradeço pela sua consideração e estamos aqui se você decidir reconsiderar. Tenha um dia incrível!', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Fico feliz que tenhamos tido essa conversa, mesmo que não tenha sido do seu interesse no momento. Agradeço pela sua atenção e estamos à disposição caso precise de nós no futuro. Tenha um excelente dia!', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Entendo perfeitamente que o serviço não seja adequado para você neste momento. Agradeço pela sua disponibilidade em ouvir e respeito sua decisão. Estamos aqui caso você mude de ideia. Tenha um dia maravilhoso!', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Obrigado por dedicar um tempo para falar comigo. Sei que este não é o serviço que você está procurando no momento. Agradeço pela cortesia e fico à disposição caso mude de ideia futuramente. Tenha um dia fantástico!', 'fail_ending', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);