INSERT INTO gerund_outgoingmessages (content, type, created_at, updated_at)
VALUES
-- HMMM
('Hmm, interessante.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Vamos ver...', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Deixe-me ver...', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ah, espera.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hmm, aguarde.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Deixa eu pensar...', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hmm, analisando.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hum, pesquisando.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ah, entendido.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ok, um momento.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hmm, processando.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bem, deixe-me ver.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hmm, vamos pensar.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hum, refletindo.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ah, vamos lá.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hmm, considerando.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ok, estou pensando.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hum, avaliando.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hmm, investigando.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ah, interessante ponto.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bem, vejamos...', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hmm, ponderando.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ok, vou verificar.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ah, estou refletindo.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hum, analisando isso.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hmm, pensando agora.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Deixe-me pensar...', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ok, estou pesquisando.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ah, um momento só.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hum, estou refletindo.', 'hmmm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);