INSERT INTO gerund_outgoingmessages (content, type, created_at, updated_at)
VALUES
-- STALLINGS
('Nossa, essa é uma pergunta interessante... Deixe-me conferir rapidinho para ter certeza.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ah, você me pegou de surpresa! Só um momentinho, vou verificar essa informação para você.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Que excelente pergunta! Estou aqui para ajudar, só preciso consultar nosso sistema rapidamente.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ah, entendi o que você está procurando. Vou pedir ao meu assistente para verificar isso enquanto conversamos.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hmm, você está me desafiando! Deixe-me investigar essa resposta enquanto continuamos nossa conversa.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Essa é uma dúvida intrigante! Permita-me buscar a resposta correta e já volto com você.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Uau, você me pegou de surpresa! Deixe-me dar uma olhada nos nossos registros e eu te falo.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Nossa, eu gostaria de ter a resposta na ponta da língua, mas vou precisar conferir essa informação para te passar certinho.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Puxa, essa é uma pergunta que eu não escuto todos os dias. Vou pesquisar para encontrar a resposta ideal para você.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hmm, essa pergunta me fez pensar. Vou precisar de um momento para acessar os dados e te fornecer a resposta adequada.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ah, que pergunta curiosa! Só preciso de alguns instantes para obter a resposta exata para você.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Interessante! Deixe-me consultar meu arquivo pessoal e trarei uma resposta que faça jus à sua pergunta.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Excelente questão! Vou pedir ao meu assistente para fazer uma busca rápida enquanto continuamos nosso bate-papo.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Nossa, isso é um desafio! Vou precisar investigar um pouco mais para te dar uma resposta completa.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hmm, essa é uma pergunta que me deixa intrigado. Deixe-me procurar a resposta correta para te dar uma informação precisa.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ah, você me pegou de surpresa! Deixe-me verificar isso e já volto com uma resposta satisfatória.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Essa pergunta me pegou desprevenido, mas não se preocupe! Vou descobrir a resposta e te dar uma resposta completa.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Bem, essa é uma pergunta interessante! Enquanto meu assistente busca pela resposta, vamos conversando um pouco mais sobre o seu interesse.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Parece que você me deu uma tarefa desafiadora. Vou fazer uma pesquisa rápida para encontrar uma resposta adequada.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Essa é uma pergunta que me deixa curioso! Só um momento, vou verificar a resposta correta para você.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Nossa, essa é uma pergunta fora do comum. Vou investigar essa informação enquanto conversamos.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Você realmente me pegou de surpresa! Permita-me pesquisar essa resposta para te fornecer uma informação precisa.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Interessante! Eu preciso verificar algumas coisas antes de poder te responder com segurança, tudo bem?', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hmm, essa é uma dúvida que eu não ouço todos os dias. Vou buscar a resposta e te fornecer o melhor que posso.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Puxa, essa pergunta é uma verdadeira incógnita! Vou pedir ao meu assistente para investigar enquanto continuamos nossa conversa.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Que interessante! Só preciso dar uma olhada rápida em nossos arquivos para encontrar a resposta adequada.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Ah, essa é uma pergunta que desperta minha curiosidade. Deixe-me checar a resposta para te dar a informação correta.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Essa pergunta realmente me deixou intrigado. Vou buscar a resposta enquanto continuamos nossa conversa.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Nossa, você me pegou desprevenido! Deixe-me pesquisar essa informação para te fornecer uma resposta precisa.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('Hmm, essa é uma pergunta que requer uma investigação mais aprofundada. Vou procurar a resposta e te passo em breve.', 'stalling', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);