INSERT INTO gerund_originalincoming (id, content, created_at, updated_at, original_incoming_id)
VALUES
-- QUESTION 1
('E aí, quais são os planos de telefone fixo que tem?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Me fala, quais são os planos de telefonia fixa disponíveis?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Opa, quero saber quais são os planos de telefone fixo que tão rolando.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Quais são os planos de telefone fixo que tem pra contratar?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Preciso saber quais são as opções de plano de telefonia fixa.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Beleza, me diz quais são os planos de telefone fixo disponíveis?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Quais são as alternativas de plano de telefone fixo pra escolher?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('E aí, tem algum plano de telefone fixo que eu possa pegar?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Me ajuda aí, quero saber quais são os planos de telefone fixo que tão oferecendo.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Quais são as opções de plano de telefone fixo que eu posso contratar?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('E aí, tem alguma opção de plano de telefone fixo disponível?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Tô querendo saber quais são os planos de telefone fixo que tem pra mim.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Qual é a variedade de planos de telefone fixo que tem aí?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Quais são as possibilidades de plano de telefone fixo que eu posso escolher?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Me fala aí, quais são os planos de telefone fixo que tão disponíveis?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Tô curioso, quais são os planos de telefone fixo que tão no mercado?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Quais são as ofertas de plano de telefone fixo que tem aí?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Tem algum plano de telefone fixo que você pode me informar?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Quais são os pacotes de telefone fixo que estão sendo oferecidos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Tô precisando saber quais são os planos de telefone fixo que tem pra contratar.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Caraca, me diz logo quais são os planos de telefone fixo, poxa!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Tá atrasado, fala logo quais são os planos de telefone fixo disponíveis!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Pô, tô sem tempo, diz logo quais são os planos de telefone fixo!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Ah, para de enrolação e me fala logo quais são os planos de telefone fixo!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Me ajuda aí, que eu tô com pressa! Quais são os planos de telefone fixo?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Tá, tá, me fala logo quais são os planos de telefone fixo, meu chapa.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Ô, amigo, tô com pressa, diz logo quais são os planos de telefone fixo disponíveis!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Vai logo ao ponto, quais são os planos de telefone fixo, rapaz?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Fala aí, sem enrolação, quais são os planos de telefone fixo!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Pô, tô com pressa, me diz quais são os planos de telefone fixo!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Tô meio sem tempo, então, quais são os planos de telefone fixo que tem?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Tá tranquilo, mas tô com pressa. Quais são os planos de telefone fixo disponíveis?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Ei, rapidinho, me diz quais são os planos de telefone fixo, por favor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Tô um pouco apressado, mas preciso saber quais são os planos de telefone fixo.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Me ajuda aí, tô meio na correria. Quais são os planos de telefone fixo que tem?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Por gentileza, poderia me informar quais são os planos de telefone fixo disponíveis?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Desculpe, estou com um pouco de pressa. Quais são os planos de telefone fixo?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Com licença, poderia me dizer quais são os planos de telefone fixo que estão disponíveis?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Por favor, poderia me orientar sobre os planos de telefone fixo?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Com todo respeito, estou com pressa. Quais são os planos de telefone fixo?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Olá, poderia me informar gentilmente quais são os planos de telefone fixo disponíveis?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Bom dia, estou interessado em saber quais são os planos de telefone fixo que vocês oferecem.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Boa tarde, poderia me ajudar a entender quais são os planos de telefone fixo disponíveis?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Oi, estou curioso para saber quais são as opções de plano de telefone fixo que posso escolher.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
('Olá, por favor, poderia me explicar quais são os planos de telefone fixo que estão disponíveis?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 1),
-- QUESTION 2
('Quais são os pacotes de celular que tem pra escolher?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Tá tendo algum plano bom de celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Quais são as opções de celular que tem pra contratar?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Quais são os planos de telefonia móvel que tão rolando?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Tem algum plano de celular legal disponível?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Quais são as alternativas de celular que eu posso pegar?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Tá tendo algum plano de celular bacana?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Me fala aí quais são os planos de celular que tão disponíveis.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Tem uns pacotes de celular que eu posso escolher?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Quais são as opções de telefonia móvel que tão disponíveis?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Quais são os planos de celular, seu idiota?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Me diz logo quais são os pacotes de celular que tem!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Tá demorando muito, fala logo quais são os planos de celular!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Quero saber quais são os planos de telefonia móvel, agora!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Tá enrolando, me fala logo os planos de celular!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Rapaz, me diz quais são os planos de celular, tá com pressa!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Quero saber logo quais são os pacotes de celular disponíveis, por favor!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Não tenho tempo pra perder, me fala os planos de telefonia móvel!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Tô com pressa, então fala aí os planos de celular!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Me diz rapidão quais são as opções de celular, tô com pressa!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Por favor, poderia me informar quais são os planos de celular disponíveis? Tô meio com pressa.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Tenho um tempinho curto, pode me dizer quais são as opções de telefonia móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Preciso saber os pacotes de celular, mas tô apressado. Pode me ajudar?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Tô com pressa, mas queria saber quais são os planos de celular. Dá pra me informar?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Não posso perder muito tempo, então me fala os planos de telefonia móvel.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Com licença, poderia me informar sobre os planos de celular disponíveis? Estou com um pouco de pressa.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Por favor, quais são as opções de telefonia móvel? Preciso saber rapidamente.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Desculpe, mas estou com pressa. Pode me dizer os pacotes de celular disponíveis?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Com todo respeito, poderia me informar os planos de celular? Estou com pressa.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Se não for incomodar, poderia me ajudar a saber quais são os planos de telefonia móvel? Estou um pouco apressado.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Olá, poderia me informar gentilmente sobre os planos de celular disponíveis?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Gostaria de saber quais são as opções de telefonia móvel, se não for incômodo.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Você poderia me ajudar a entender os pacotes de celular disponíveis, por favor?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Poderia me fornecer informações sobre os planos de celular? Estou interessado em saber.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
('Por favor, poderia me orientar sobre as opções de telefonia móvel? Estou tranquilo para ouvir.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 2),
-- QUESTION 3
('Qual a diferença entre o plano Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Me diz, qual a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Cê sabe me dizer a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Ei, me explica aí, qual é a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Aí, qual é o lance entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Tô na dúvida, me ajuda, o que que muda entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Mano, você sabe a treta entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('E aí, tem como tu me dizer qual é a parada do Viva ilimitado plus e do Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Me diz aí, qual é o babado do Viva ilimitado plus e do Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Cê tá ligado na diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Tô querendo entender a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra, pode me ajudar?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Ei, me tira uma dúvida, qual é a parada entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Fala aí, qual é a pegada do Viva ilimitado plus e do Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Oi, queria saber qual é a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra, você sabe?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('E aí, tem como me explicar a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Me conta aí, qual é o rolê do Viva ilimitado plus e do Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Pode me ajudar a entender o que que muda entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Tô na dúvida, você pode me explicar a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Me fala, qual é a parada entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Mano, me dá uma ideia, qual é a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('O que muda entre o Viva ilimitado plus e o Viva ilimitado plus extra, caramba?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Qual é a porra da diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Me diz logo qual é a merda que muda entre o Viva ilimitado plus e o Viva ilimitado plus extra!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Tá esperando o quê pra me contar a putaria que tem entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Desembucha aí, porra! Quero saber qual é o caralho da diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Ei, ó, qual é a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra? Vai logo!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Me diz rápido, qual é a parada entre o Viva ilimitado plus e o Viva ilimitado plus extra, por favor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Ô, moço, tô com pressa, só quero saber a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Oi, tô com pouco tempo aqui, pode me falar qual é a pegada do Viva ilimitado plus e do Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Tá enrolando pra quê? Quero saber logo qual é a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra!', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Me ajuda aqui, tô com pressa. Qual é a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Tô com um tempinho curto, mas preciso saber: o que que muda entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Pode me dizer rapidinho qual é a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Tô com um pouco de pressa, mas queria entender a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Tenho que ir logo, mas antes me fala, qual é o lance entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Por favor, poderia me explicar a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra? Estou com um pouco de pressa.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Me desculpe, mas tenho pouco tempo. Será que você pode me informar a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Com licença, estou com pressa, mas preciso saber: qual é a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Desculpe incomodar, mas tenho uma urgência. Você poderia me dizer brevemente a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Peço desculpas pela pressa, mas será que você pode me esclarecer a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Olá, tudo bem? Poderia me ajudar a entender a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Bom dia! Você saberia me explicar qual é a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Oi, desculpe interromper, mas estou com uma dúvida. Pode me esclarecer a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Boa tarde! Será que você pode me informar brevemente a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
('Desculpe a pergunta, mas gostaria de entender a diferença entre o Viva ilimitado plus e o Viva ilimitado plus extra.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 3),
-- QUESTION 4
('Tem algum contrato mínimo pra fechar esses planos, é?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Precisa ter um contrato mínimo pra aderir aos planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Rapaz, pra assinar esses planos, tem que ter um contrato mínimo?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Ah, tem algum contrato mínimo pra entrar nos planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Pode me dizer se tem algum contrato mínimo pra fechar esses planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Preciso saber se tem algum contrato mínimo pra assinar os planos, tá ligado?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Ei, tem algum contrato mínimo pra entrar nos planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Eu queria saber se tem algum contrato mínimo pra aderir aos planos, sabe?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Se eu quiser assinar esses planos, tem que ter um contrato mínimo?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Me diz aí, tem algum contrato mínimo pra fechar esses planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Queria saber se tem contrato mínimo pra entrar nos planos, mano.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Ah, é necessário ter um contrato mínimo pra assinar os planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('E aí, tem algum contrato mínimo pra aderir aos planos, parceiro?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Me fala aí, tem algum contrato mínimo pra fechar esses planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Ô, tem contrato mínimo pra entrar nos planos, sabe dizer?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Será que tem algum contrato mínimo pra assinar esses planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Preciso saber se tem algum contrato mínimo pra aderir aos planos, entende?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('E aí, tem algum contrato mínimo pra fechar esses planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Queria saber se tem contrato mínimo pra entrar nos planos, beleza?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Ah, é necessário ter um contrato mínimo pra assinar os planos, tá tranquilo?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Qual o contrato mínimo pra assinar esses planos, mano?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Pô, tem contrato mínimo pra fechar esses planos ou não?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Ei, contrato mínimo pra entrar nos planos, tem ou não tem?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Se liga, tem contrato mínimo pra assinar esses planos, velho?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Ô, tem ou não tem contrato mínimo pra fechar esses planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Peraí, tem algum contrato mínimo pra assinar esses planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Sabe dizer se precisa ter contrato mínimo pra fechar esses planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Tá ligado se tem contrato mínimo pra entrar nos planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Me fala aí, precisa ter contrato mínimo pra assinar esses planos ou não?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Ah, tem ou não tem contrato mínimo pra fechar esses planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Qual é o lance do contrato mínimo pra assinar esses planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Me explica se tem contrato mínimo pra fechar esses planos, por favor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Você sabe se precisa ter contrato mínimo pra entrar nos planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Pode me informar se tem contrato mínimo pra assinar esses planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Ah, tem contrato mínimo pra fechar esses planos ou não?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Por favor, poderia me dizer se há algum contrato mínimo para assinar os planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Gostaria de saber se é necessário ter contrato mínimo para fechar esses planos.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Você sabe informar se existe contrato mínimo para entrar nos planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Poderia me esclarecer se é preciso ter contrato mínimo para assinar esses planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Ah, por gentileza, tem contrato mínimo para fechar esses planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Desculpe, mas gostaria de saber se há algum contrato mínimo para assinar os planos.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Poderia me informar se existe algum contrato mínimo para fechar esses planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Você sabe dizer se é necessário ter algum contrato mínimo para entrar nos planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Por favor, poderia me esclarecer se é preciso ter algum contrato mínimo para assinar esses planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
('Ah, poderia me explicar se há contrato mínimo para fechar esses planos?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 4),
-- QUESTION 5
('Dá pra escolher planos diferentes pra telefone fixo e celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Tem como eu escolher planos diferentes pra telefone fixo e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Posso optar por planos distintos pra telefone fixo e celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('É possível ter planos diferentes pra telefone fixo e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Eu posso ter planos diferentes pra telefone fixo e celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Dá pra escolher planos separados pra telefone fixo e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Posso pegar planos diferentes pra telefone fixo e celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('É permitido ter planos distintos pra telefone fixo e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Tem como eu ter planos diferentes pra telefone fixo e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Posso optar por planos separados pra telefone fixo e celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('É possível ter planos diferentes pra telefone fixo e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Eu posso ter planos diferentes pra telefone fixo e celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Dá pra escolher planos distintos pra telefone fixo e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Posso pegar planos diferentes pra telefone fixo e celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('É permitido ter planos distintos pra telefone fixo e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Tem como eu ter planos diferentes pra telefone fixo e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Posso optar por planos separados pra telefone fixo e celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('É possível ter planos diferentes pra telefone fixo e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Eu posso ter planos diferentes pra telefone fixo e celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Dá pra escolher planos distintos pra telefone fixo e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Pode ter plano diferente pra telefone fixo e móvel, né?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Planos diferentes pra telefone fixo e celular, tem?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Escolho plano separado pra telefone fixo e móvel, tá ligado?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Eu posso ter plano diferentão pra telefone fixo e celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Tô afim de planos diferentes pra telefone fixo e móvel, saca?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Posso escolher planos diferentes pra telefone fixo e móvel, né?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Tem como eu ter planos diferentes pra telefone fixo e celular, meu chapa?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Eu posso optar por planos separados pra telefone fixo e móvel, camarada?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('É possível ter planos distintos pra telefone fixo e móvel, mano?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Dá pra eu pegar planos diferentes pra telefone fixo e celular, meu brother?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Posso escolher planos diferentes pra telefone fixo e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Tem como eu ter planos diferentes pra telefone fixo e celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Eu posso optar por planos separados pra telefone fixo e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('É possível ter planos distintos pra telefone fixo e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Dá pra eu pegar planos diferentes pra telefone fixo e celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Por gentileza, poderia informar se é possível escolher planos diferentes para telefonia fixa e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Haveria a opção de ter planos distintos para telefone fixo e celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('É permitido optar por planos separados para telefone fixo e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Gostaria de saber se é possível ter planos diferentes para telefone fixo e móvel, por favor?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Seria viável pegar planos diferentes para telefone fixo e celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Olá, você poderia me informar se é possível escolher planos diferentes para telefonia fixa e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Será que tem como eu ter planos distintos para telefone fixo e celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Eu gostaria de saber se é permitido optar por planos separados para telefone fixo e móvel.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Poderia me informar se é possível ter planos diferentes para telefone fixo e móvel?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),
('Você sabe se dá para pegar planos diferentes para telefone fixo e celular?', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 5),